--INSERT INTO favorites
--    (id, family, "category", url)
--VALUES
--    ('Cookie','Cookie', 'Handwriting', 'https://fonts.google.com/specimen/Cookie');
--
--INSERT INTO Favorites
--    (id, family, "category", url)
--VALUES
--    ('Press%20Start%202P','Press Start 2P', 'Display', 'https://fonts.google.com/specimen/Press%20Start%202P');